user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
